### ISSUE TITLE
linear indexing style seems like it would be much preferable

### ISSUE THREAD

**Issue by nsajko** [giordano/FixedSizeArrays.jl#5]
Switching the type to the linear indexing style, like [here](https://gitlab.com/nsajko/FixedSizeColumnMajorDenseArrays.jl/-/blob/2e0bcedeb8e3a299b6758ef91bb1069c757208f6/src/FixedSizeColumnMajorDenseArrays.jl#L37-41), would both:

* enable better efficiency for generic user code

* decrease the amount of code required in the implementation here

Am I misunderstanding something?

**Comment by giordano** [comment]
PR welcome.
